`timescale 1ns / 1ps

module tb_ldpc_encoder_comb;

    // Parameters
    localparam int K             = 128;
    localparam int PARITY_BITS   = 16;
    localparam int N             = K + PARITY_BITS;

    // DUT signals
    logic [K-1:0] message_i;
    logic [N-1:0] codeword_o;

    // Expected values
    logic [K-1:0] expected_message;
    logic [N-1:0] expected_codeword;
    integer vector_file;
    integer scan_result;
    integer test_count;
    integer pass_count;
    integer fail_count;

    // DUT
    ldpc_encoder #(
        .K(K),
        .PARITY_BITS(PARITY_BITS)
    ) dut (
        .message_i(message_i),
        .codeword_o(codeword_o)
    );

    // Apply one test vector
    // The encoder is fully combinational
    // #1 is only used to let the combinational logic settle in simulation
    // It does NOT represent encoder latency
    task automatic check_vector(
        input logic [K-1:0] message,
        input logic [N-1:0] expected
    );
    begin

        message_i <= message;

        #1;

        test_count = test_count + 1;

        if (codeword_o === expected) begin
            pass_count = pass_count + 1;
        end

        else begin
            fail_count = fail_count + 1;
            $display("");
            $display("FAIL - Test %0d", test_count);
            $display("Message  : %032h", message);
            $display("Expected : %036h", expected);
            $display("Received : %036h", codeword_o);
            $display("");
        end
    end
    endtask

    // Stimulus
    initial begin

        message_i = '0;

        test_count = 0;
        pass_count = 0;
        fail_count = 0;
        
        $display("");
        $display("------------------------------------------------");
        $display("LDPC combinational encoder testbench");
        $display("K = %0d, N = %0d, parity = %0d", K, N, PARITY_BITS);
        $display("------------------------------------------------");
        $display("");

        // Open reference vectors generated by Python
        vector_file = $fopen("encoder_test_vectors.txt", "r");

        if (vector_file == 0) begin
             $fatal(1, "Could not open encoder_test_vectors.txt");
        end

        // Read and test every vector
        // File format: <128-bit message hex> <144-bit expected codeword hex>
        while (!$feof(vector_file)) begin
            scan_result = $fscanf(vector_file, "%h %h\n", expected_message, expected_codeword);

            if (scan_result == 2) begin
                check_vector(expected_message, expected_codeword);
            end
        end

        $fclose(vector_file);

        // Results
        $display("------------------------------------------------");
        $display("Simulation results");
        $display("------------------------------------------------");
        $display("Tests  : %0d", test_count);
        $display("Passed : %0d", pass_count);
        $display("Failed : %0d", fail_count);
        $display("------------------------------------------------");

        if (fail_count == 0) begin
            $display("");
            $display("ALL TESTS PASSED");
            $display("");
        end
        else begin
            $fatal(1, "%0d LDPC encoder tests failed", fail_count);
        end

        $finish;

    end

endmodule